### PR TITLE
PDTWO-146: add Packstation support

### PR DESCRIPTION
**Pull request by sprankhub**
This is an attempt to add packing station support. As soon as this is merged, I would also like to add support for PO boxes ("Postfach"), post offices ("Postfiliale") and big recipients ("Großempfänger").
But first, please review if the code is fine for you or if you need changes :-)

To be honest, I did not check the tests at all. Do you think we need to update / extend the tests to reflect these changes?

### CODE REVIEW

**Comment by sprankhub** [comment]
Any chance that this gets reviewed and eventually merged? Thanks!

**Comment by mam08ixo** [comment]
> Do you think we need to update / extend the tests to reflect these changes?

Tests are the best way to demonstrate how a feature is supposed to work. So yes, adding a test for the Packstation use case seems to be beneficial. We will take care of that.

~Did you ever succeed to get Packstation data corrected by the web service? In my tests, it just mirrors the wrong data.~ Nevermind, you better not use the sandbox endpoint…

**Comment by mam08ixo** [comment]
Thank you for your contribution, @sprankhub – you did an amazing job here figuring out what needs to be done and where. Sorry it took such a long time to get reviewed.

**Comment by sprankhub** [comment]
Thanks for the kind words and thanks for finishing and merging it!

**Pull request merged**
